const portfolios = [
  {
    id: 1,
    category: "HTML/CSS",
    link1: "https://github.com/Shikha-1/layout-task3/",
    link2: "https://shikha-1.github.io/layout-task3/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets8.lottiefiles.com/packages/lf20_jhlaooj5.json",
    title: "Photography Webpage",
    placholder: `A SPA designed to show & promote work of a photography company.`,
  },
  {
    id: 2,
    category: "Javascript",
    link2: "https://shikha-1.github.io/quiz-app/",
    link1: "https://github.com/shikha-1/quiz-app/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets7.lottiefiles.com/private_files/lf30_6ocpfdil.json",
    title: "Quiz App",
    placholder: `Generates random questions, then display score & high scores on the basis of consecutive performances.`,
  },
  {
    id: 3,
    category: "Javascript",
    link1: "https://github.com/shikha-1/Music_Player/",
    link2: "https://shikha-1.github.io/Music_Player/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets7.lottiefiles.com/private_files/lf30_0RVw24.json",
    title: "Music Player",
    placholder: `A SPA which performs all the functionalities of a music player.`,
  },
  {
    id: 4,
    category: "React Js",
    link1: "https://github.com/shikha-1/Netflix-Clone/",
    link2: "https://cranky-sammet-db1209.netlify.app/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets4.lottiefiles.com/private_files/lf30_F6EtR7.json",
    title: "Netflix-Clone",
    placholder: `A netflix like SPA which when clicked on the specific movie poster, shows trailer of that movie.`,
  },
  {
    id: 5,
    category: "React Js",
    link1: "https://github.com/Shikha-1/to-do-app.git",
    link2: "https://sleepy-benz-633680.netlify.app/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets5.lottiefiles.com/packages/lf20_jy1bgnpp.json",
    title: "React To Do App",
    placholder: `It organizes tasks with a list that can make everything much more manageable.`,
  },
  {
    id: 6,
    category: "Node Js",
    link1: "https://github.com/Shikha-1/DelhiWeather",
    link2: "https://cryptic-anchorage-58304.herokuapp.com/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets6.lottiefiles.com/packages/lf20_ni4ztgup.json",
    title: "Delhi Weather",
    placholder: `It shows weather & weather description of Delhi.`,
  },
  {
    id: 7,
    category: "Javascript",
    link1: "https://github.com/Shikha-1/PostMaster/",
    link2: "https://shikha-1.github.io/PostMaster/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets1.lottiefiles.com/private_files/lf30_wqypnpu5.json",
    title: "Postman Clone",
    placholder: `Basically a small version of Postman. It provides all the features of Postman but only for GET & POST requests.`,
  },
  {
    id: 8,
    category: "Javascript",
    link1: "https://github.com/shikha-1/Covid19_stats/",
    link2: "https://shikha-1.github.io/Covid19_stats/",
    icon1: "Code",
    icon2: "Demo",
    image: "https://assets9.lottiefiles.com/private_files/lf30_DtdYns.json",
    title: "Covid-19 Stats",
    placholder: `It shows covid cases of countries across the globe.`,
  },
  {
    id: 9,
    category: "Javascript",
    link1: "https://github.com/Shikha-1/daily_news",
    link2: "https://shikha-1.github.io/daily_news/",
    icon1: "Code",
    icon2: "Demo",
    image:
      "https://assets4.lottiefiles.com/datafiles/KbKSrbWahtNPvY6/data.json",
    title: "Daily News",
    placholder: `Shows daily top 10 news headlines of India`,
  },
];
export default portfolios;